.TH "source/ascon/ascon.h" 3 "Version 0.1.0" "VERUM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/ascon/ascon.h \- Ascon shared primitives\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'standard/types\&.h'\fP
.br
\fR#include 'define\&.h'\fP
.br
\fR#include 'auxiliary/memory\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Ascon shared primitives\&. 

This header defines shared constants, types, and internal helper functions for the Ascon family of authenticated encryption algorithms\&.

.PP
\fBSee also\fP
.RS 4
https://doi.org/10.6028/NIST.SP.800-232
.RE
.PP
\fBCopyright\fP
.RS 4
(C) Core Labs All rights reserved\&.
.RE
.PP
\fBAuthor\fP
.RS 4
Manoel Serafim @email manoel.serafim@proton.me @github https://github.com/manoel-serafim SPDX-License-Identifier: GPL-3\&.0 
.RE
.PP

.PP
Definition in file \fBascon\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VERUM from the source code\&.
