.TH "include/auxiliary/endian.h" 3 "Version 0.1.0" "VERUM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/auxiliary/endian.h
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
(C) Core Labs All rights reserved\&.
.RE
.PP
\fBAuthor\fP
.RS 4
Manoel Serafim @email manoel.serafim@proton.me @github https://github.com/manoel-serafim SPDX-License-Identifier: GPL-3\&.0 
.RE
.PP

.PP
Definition in file \fBendian\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VERUM from the source code\&.
