.TH "source/auxiliary/memory.c" 3 "Version 0.1.0" "VERUM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/auxiliary/memory.c \- Memory primitives\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'auxiliary/memory\&.h'\fP
.br
\fR#include 'define\&.h'\fP
.br
\fR#include 'standard/types\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Memory primitives\&. 

Defines fixed-size memory operations optimized for 32-bit embedded targets, using explicit aligned word accesses to preserve predictable instruction generation and bounded code footprint\&.

.PP
\fBCopyright\fP
.RS 4
(C) Core Labs All rights reserved\&.
.RE
.PP
\fBAuthor\fP
.RS 4
Manoel Serafim @email manoel.serafim@proton.me @github https://github.com/manoel-serafim SPDX-License-Identifier: GPL-3\&.0 
.RE
.PP

.PP
Definition in file \fBmemory\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VERUM from the source code\&.
